version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: _docker/nginx/Dockerfile
        volumes:
            - ./var/www:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./_docker/nginx/ssl/:/etc/nginx/ssl/
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
        container_name: app_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./var/www:/var/www
        depends_on:
            - mysql
            - redis
            - mongo
        container_name: app_project

    mysql:
        image: mysql:8.0
        restart: always
        volumes:
            - ./_docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: app_mysql

    redis:
        image: redis:latest
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ./_docker/redis/data:/var/lib/redis
            - ./_docker/redis/conf:/usr/local/etc/redis/redis.conf
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        container_name: app_redis

    mongo:
        image: mongo
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - ./_docker/mongo/db:/data/db
            - ./_docker/mongo/configdb:/data/configdb
            - ./_docker/mongo/dump:/dump
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        container_name: app_mongo

    nodejs:
        build:
            context: .
            dockerfile: _docker/nodejs/Dockerfile  # Adjust the path and filename accordingly
        volumes:
            - ./var/www:/var/www
        ports:
            - 3000:3000  # Adjust the port if needed
        depends_on:
            - redis
            - mongo
        container_name: app_nodejs