version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: _docker/nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./_docker/nginx/ssl/:/etc/nginx/ssl/
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
        container_name: app_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: app_project

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./_docker/tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: chat_loc
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: app_db
